### ISSUE TITLE
Rewritting Fields

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#438]
I have rewritted a bit AccessLevel. And before rewriting the similar fields I prefer asking you: https://github.com/Eighke/fof/blob/4165edceae37cfa0cd2c250f68af486035562315/fof/Form/Field/AccessLevel.php

The current method `getStatic` and `getRepeatable` are alike. The only difference is about what we are doing with `id`. So I created only one method to manage both (I had no idea about the method name as usual... :)).

I also added a new attribute `showinput`, if enabled it will return the `getInput` instead of the current method (It can be needed sometime, for show only or with JS). It can be added in the Render directly if we need it for every fields.

**Comment by nikosdion** [comment]
Name the method getFieldContents, make it protected and add a docblock. As for the attribute, I would rename it to "legacy" since you're using the legacy method provided by Joomla!.

**Comment by Eighke** [comment]
You're the best. =)

Ok, I started to apply this change to the similar fields. I'll make a PR this week.

**Comment by Eighke** [comment]
Hi Nicholas, some question:

- Email: Removing the `url` attribute on `getRepeatable`, we already have Url field for that. It just duplicate the field behavior.
- GenericList: Shouldn't we remove `show_link` attribute and use only `url`? No URL mean we haven't link. Same question for other Fields using `show_link`.
- ImageList: Shouldn't it return a list of image (using Option)? If we need just a single image we already have Image and Media.
- Rules: Do you think we can use the J! one?

**Comment by Eighke** [comment]
Last question, in some fields (User / Timezoen and GroupedList) you have hard coded some CSS (e.g. fof-groupedlist-group) can we remove it?

**Comment by nikosdion** [comment]
* Email: No. If you read the code you'll see that if the URL is empty we populate it automatically. If you remove the show_link attribute then we'll always be showing a link. Of you remove the automatic link population you are removing useful and desired functionality.
* GenericList: Yes, as long as the URL is NOT populated automatically.
* ImageList: No. ImageList extends JFormFieldImagelist and shows a drop-down list of filenames. Media (and its alias Image) show an image selection dialog using com_media. Different use cases, different UI, please don't touch it.
* Rules. No! RTFD (Read the fine docblock). I am copying it here: "At the timing of this writing (2013-12-03), the Joomla "rules" field is buggy. When you are dealing with a new record it gets the default permissions from the root asset node, which is fine for the default permissions of Joomla articles, but unsuitable for third party software. We had to copy & paste the whole code, since we can't "inject" the correct asset id if one is not found. Our fixes are surrounded by `FOF Library fix` remarks."
* "Hardcoded CSS". No. Do not remove anything. These CSS classes are there for a reason, namely being able to format grouped lists differently than drop-down lists, i.e. something that Joomla! doesn't allow you to do.

**Comment by Eighke** [comment]
- Email: Uhm you mixed the Email and GenericList. :), I'm speaking about `Url`. In the `getStatic` of this field you have only one behavior: it will show an email link (mailto:). But on the `getRepeatable` you have 2 behavior: the same as getStatic and the same as `Url::getRepeatable()` (a normal link). The second behavior is redundant and can be deleted. If you need a link you should use URL not Email.
- ImageList: Yes the `getInput` are completly different. I'm speaking about the `getStatic`. Both are basically the same (they show the image). The only difference is the $path used on ImageList. I wanted do make the both Field more different little bit useless to have twice the same behavior :/).
- Rules: Yes I already read it, but 2013-12-03 is more that 1 years ago. So I needed to know if it was still break of not. :)
- CSS: Ok, can we make the name a little bit shorter? :)

**Comment by nikosdion** [comment]
* No, I did NOT mix the Email and GenericList fields up. I am very clear in what I am saying about the Email and GenericList fields. Email.php lines 150:162; GenericList.php lines 125:137. Please read the code *extremely* carefully and the read it another five times to make sure you understand what's going on.
* ImageList. As you will see each class is extending from a different JFormField class. Since we're PHP 5.3 compatible (there is no support for traits) you can't simplify these fields. Well, when we drop PHP 5.3 support at some point in the future rest assured that by using traits we can reduce the code in the Form package by 50% or more.
* Rules. You assume that Joomla! has changed in the meantime, _without_ a new major version coming out? No, it hasn't changed and won't change in the 3.x release branch as that would be backwards incompatible.
* CSS. No. I want to make sure the names are unique enough and obvious enough.

**Comment by nikosdion** [comment]
Regarding Email: we might want to display a *customised* email link, something like mailto:someone@example.com?subject=Enquiry&cc=someone.else@example.com&body=Hello,+world  This is why the url attribute is there and, trust me, it does come in handy ;)

Regarding traits: amen to that. I have a lot of copy-pasted code in the base MVC objects regarding $this->input handling and calling handlers / plugins. With traits I could write these ~120 lines once. Without traits I had to copy it four or five times. And that's just the tip of the iceberg.

Regarding Rules. LOL! You can never know. Right now Joomla! 4 is not even a listed goal of the PLT. Hope dies last, I guess.

**Comment by Eighke** [comment]
Email: Oh, right, didn't think about that. Couldn't we hardcore the `mailto:`? And I could be nice to use `parseFieldTags` on it. I would like to replace someone@example.com but the row value. :)

Traits & Rules: I hope I will live long enough to use PHP 5.4... ^^'

**Comment by nikosdion** [comment]
Email: Hm, I though we already did. Apparently we don't. Yes, please hardcode "mailto:" or, if it's present in the URL, filter it out. And yes, do use parseFieldTags.

**Comment by Eighke** [comment]
PR done.

Except `Title` and `Tag`, it is untested. I make a lot of boring copy / paste (Traits, traits~), and even if I read 3 times the code some mistakes could still be here.

We don't have unit test for fields right? I will make the tests after FOF3 can be tested.

**Comment by Eighke** [comment]
Ah also, for the `Title` and `Tag` I can PR the backport for FOF2 if you want (it is already done for the test so...).

**Comment by nikosdion** [comment]
I hear ya regarding traits. One of my immediate concerns is warning people on PHP 5.3 to upgrade to PHP 5.5 (5.4 will be EOL in August 2015). I plan to drop PHP 5.3 support in August, the reasoning being that I can support one EOL version, but not **two** EOL versions, while keeping a modicum of sanity.

**Comment by Eighke** [comment]
Oh, great. I didn't notice that PHP 5.4 will be soon EOL. The good news is that some big hosters started to remove PHP 5.3, like OVH : http://travaux.ovh.net/?do=details&id=12455 (OVH is the 1st biggest hoster in europe).

Well 6 months to go. :D

Ah, I'll PR the backport for FOF2 tomorrow.

**Comment by nikosdion** [comment]
I'll start warning users that we'll drop PHP 5.3 support in May (practically it'll be in August, I just need them to switch before I change my code). Let's see how that goes :)

**Comment by Eighke** [comment]
Yup good idea. I checked and 1and 1 already removed 5.3. So I think most of the hosters will have removed 5.3 in August. :)
