### ISSUE TITLE
Hit() function

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#472]
Nicholas, I see you removed hit() from the model, do you thing to reimplement it later or not? If not I was thinking about creating a new behavior.

**Comment by nikosdion** [comment]
There's no point implementing it. When you are using Joomla! caching, a caching proxy (e.g. Varnish) or a CDN the code never runs, therefore never registers a hit. As a result the hit counter is a stupid idea in this date and time because:
- It doesn't work in a meaningful way when you most need it (high traffic sites)
- The additional write to the database is unnecessarily slowing down the page load and has adverse effects to the database server's cache.

**Comment by Eighke** [comment]
Oh I never thought about caching proxy or CDN. Right. I will just create a behavior so. Wanna include it in FOF3?

**Comment by nikosdion** [comment]
I'd rather not have it in FOF. You can now easily attach behaviors to your models without having to put them in core.

**Comment by Eighke** [comment]
Oki. It is just that it is good to have "generic" behavior in the core for the community. Everybody could use it w/o redeveloping it. And because it is a behavior it have no real impact on anything else in the code. :)

**Comment by nikosdion** [comment]
Except the people asking me why there's a bug in the Hit behavior, because it doesn't register a hit when they are using Joomla! cache, a caching proxy or a CDN...

**Comment by Eighke** [comment]
Uhuh, well said like that it is a problem. :)

Oki. :)
