### ISSUE TITLE
MagicFactory question

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#481]
Hi Nicholas,

I have a question regarding the `MagicFactory` behaviour and the "old" FOF2 behaviour.

FOF2 behaviour is:

1/ If the Model doesn't exists FOF will "magic` create one, then `magic` config it with `fof.xml`.
2/ If the Model exists, only `magic` config it with `fof.xml`

In FOF3 we lost the 2/. So if we get a simple case:

- I have a very simple component, and I'm using only my fof.xml and my Views.
- Later on, I need to add a simple method in my Model, so I create my Model.
- Everything break because fof.xml is not loaded anymore for this model.

I searched inside the wiki. But nothing speaks clearly about loosing the fof.xml configuration in this case. It makes the MagicFactory less convenient to use. :/

So my question is, is it a needed behaviour or not? If yes we need to write it more clearly in the wiki.

**Comment by nikosdion** [comment]
FOF 2 was wrong on #2. If there’s a concrete class it shouldn’t have its behaviour modified by fof.xml. This is even more important considering the options cascade (common to site/admin and the catch-all * notation to specific model/view). It would result in unexpected behaviour. Moreover, it was really damn slow. The way FOF 3 works is the intended behaviour. That was how I wanted to have coded it in FOF 2 but I couldn’t for several architectural reasons.

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by Eighke** [comment]
Yup, but here in final it will make people "losing time" creating `fof.xml` configuration that will not be used after. I can see the case where someone create the complete `fof.xml` relations and realize after that it is not working (and complain why~).

Well, I like this behaviour (it allow to create a component very fast and optimize it later). The main problem is the wiki. Currently the wiki doc looks pretty similar that FOF2 behaviour. Can be confusing.

**Comment by nikosdion** [comment]
“Similar” is the key word. I never said “identical” :) Besides, the documentation does say that the fof.xml configuration works on magically created classes. Do you have a specific change you had in mind for the documentation?

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by Eighke** [comment]
> fof.xml configuration for the Controller, Model and View IS taken into account.

That line. :)
It should be changed by something like 

> fof.xml configuration for the Controller, Model and View IS taken into account if the class is magic created.

 :)

**Comment by nikosdion** [comment]
I think you can edit the wiki yourself ;)

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by Eighke** [comment]
Right. :)

Question, the Toolbar is the only exception here. Currently the Toolbar is magic created in the `DefaultFactory` and`MagicFactory` is always loading  `fof.xml`. So currently the Toolbar has the same behaviour that FOF2 when you are using the `MagicFactory`.

Do you forgot to change the behaviour or it is the needed one?

**Comment by nikosdion** [comment]
That’s because there is only one Toolbar per component. It makes perfect sense to configure it with fof.xml when you don’t have a specialised toolbar class.

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by Eighke** [comment]
Yes, but currently even if you have a specialised toobar class, this Toolbar will be configure using fof.xml.

You also have only one Dispatcher and one TransparentAuthentication, but the behaviour is not the same.

**Comment by nikosdion** [comment]
> Yes, but currently even if you have a specialised toobar class, this Toolbar will be configure using fof.xml.
> 
Not quite. The specialised methods override the configuration. Even though the configuration is loaded there is no guarantee that it will be honored. To put it simply, it’s up to you, the developer, to decide if the configuration has any effect on the specialised class.
> You also have only one Dispatcher and one TransparentAuthentication, but the behaviour is not the same.
> 

Dispatcher and TA configuration is read automatically as long as you don’t have a specialised class. Considering exactly why you would need to create specialised classes for them and what you can configure in fof.xml for them you’ll see that it makes sense.

For example, the only thing you can configure in the dispatcher is the default view. If you only need to change the default view it makes sense to configure it through fof.xml. If you’re going to override the class to add onBeforeDispatch it makes more sense to override the protected variable instead of going through a different file.

TA is even more specific. The only reason to create a custom TA class is to completely override how TA performs authentication. This makes passing configuration variables to it rather moot, since you’re not going to follow FOF’s TA method.

Finally, read the Toolbar and Render classes’ code. You’ll see exactly why Toolbar had to break the rule for loading the configuration.

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by Eighke** [comment]
So Toolbar is an hybrid. :). Ok I got it.
