### ISSUE TITLE
Edit trigger onBeforeSave

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#488]
I have a small problem. I needed to add some check in the onBeforeSave inside my model when a item is saved ($task = save). The problem is than onBeforeSave is triggered by `checkIn` and `lock` in `DataController::edit()` so my onBeforeSave is triggered in the wrong place.

Currently the solution is to use `onBeforeApplySave` in the Controller.

But it is not really intuitive. For all other methods (archive, copy, publish, etc) the events are called in the Model, applySave is the only exception where events are called in the Controller.

Couldn't we use a applySave() method in the Modal and move the events inside?

**Comment by nikosdion** [comment]
You gave the answer yourself. You want something to run when a specific *Controller task* executes. Therefore the architecturally correct place to put the code is the Controller, not the Model, since the Model must not know what the Controller is doing (or if a Controller exists at all – you could be calling the Model from another Model).

**Comment by Eighke** [comment]
What I don't get is why all the other `Controller` method (orderup, remove, etc) has there own method and events in the `Model` except `applySave`? All those method in Controller are basically the same so there behaviour should be the same.

Why the other methods don't have any events in the Controller but in the Model instead?

That also means it is impossible to create a Model behavior for it (and controller has no behaviour :().

**Comment by nikosdion** [comment]
Because you are seeing it the wrong way around. Forget about the Controller. You only have a DataModel.

Should you be able to tell the model to change the ordering of an item? Yes. Therefore the methood belongs to the Model.

Should you be able to tell the model to trash, delete or undelete an item? Yes. Therefore the methood belongs to the Model.

Should you be able to tell the model to save an item? Yes. Therefore the methood belongs to the Model.

Should you be able to tell the model to save an item *and then reload the edit page*? NO!!! The Model does not know anything about pages, views and tasks. Therefore apply belongs to the Controller.

This poses an interesting dilemma when writing the Controller implementation. We have three possible tasks for saving data: save, apply and savenew. The only difference is what they do *after* the Model has saved the item. What is done *before* is the problem. The Controller is aware of the shape of the data it receives and responsible to transform it into a suitable Model state. Therefore it's fair to assume that the input data will need some pre-processing before any of these three methods runs.

This would require us to implement three different events: onBeforeSave, onBeforeApply and onBeforeSavenew. In order to save code duplication we'd have to create a method which would be called by all three event methods. Moreover, on the base Controller itself, we'd have to triplicate the code for pre-save checks. That's an awful lot of code duplication!

Instead of repeating ourselves I decided to create the applySave method in the base DataController. This solves the code duplication in both situations:

* The common pre-save checks for the base save, apply, savenew methods is put in applySave. The methods only call applySave and then perform a different redirection on success.
* Your controller can hook into the onBeforeApplySave which lets you handle the input transformation into Model state without code duplication and without the need to create yet another protected method.

This results in more maintainable, architecturally correct code.

Therefore, depending on what you're doing, you need to specialise one of the following methods:

* The controller's onBeforeApplySave if you are transforming input data into something your Model can act upon or if you're checking the validity of the input data specifically for the actions which lead into the applySave method to be called.
* Model's check() if you're checking the validity of the input data regardless of its origin.
* Model's onBeforeSave() if you're manipulating the raw data sent to the Model to be saved (e.g. implementing the pre-save state save portion of an event which fires only when specific fields are modified, like we do in Akeeba Subscriptions).

Now you see why onBeforeApplySave has no place in the Model? It's a Controller thing, designed to reduce code duplication.

**Comment by Eighke** [comment]
> Should you be able to tell the model to save an item and then reload the edit page? NO!!! The Model does not know anything about pages, views and tasks. Therefore apply belongs to the Controller.

I don't want to tell the model to save and reload, I want to tell the model to `unlock` before `save`. The goal is not to add everything from the `applySave` inside the Model, but only the L.1333-1345. Exactly like the other Controller methods.

```php
$eventName = 'onBeforeApplySave';
$result = $this->triggerEvent($eventName, array(&$data));

if ($id != 0)
{
	// Try to check-in the record if it's not a new one
	$model->unlock();
}

// Save the data
$model->save($data);

$eventName = 'onAfterApplySave';
```
TO
```php
$model->applySave($data);
```.

And in the Model::applySave just doing the same code. So nothing like View or Controller or anything else are involved. Only the model.

**Comment by nikosdion** [comment]
Locking is performed by the controller when you edit a record. Unlocking is performed after the record is saved. The model itself doesn't give a damn if the record is locked or not: this is something used by the controller only. If you're trying to unlock a record before the model saves it you are probably using the wrong solution to your problem.

**Comment by Eighke** [comment]
I don't want to unlock anything. I just proposed that all the methods in the Controller use the same behaviour and structure.

My problem is that I need to create a behaviour on the Controller::applySave(), and it is not possible. It is the only exception, all the other Controller methods have there own Model method and event except applySave. :/

If controller could have behaviours it should be fine but here I'll need to add my onBeforeApplySave on every controller instead of just adding a behaviour.

**Comment by nikosdion** [comment]
Use a PHP 5.4 and later feature: Traits.

**Comment by Eighke** [comment]
Yes that what I'll do, but I wanted to avoid the class and pass the behaviour using fof.xml <model>.

**Comment by nikosdion** [comment]
You can't.

**Comment by Eighke** [comment]
:-(. You're evil. ^^

Btw. When have you planned to switch fof3 to development?

**Comment by nikosdion** [comment]
Soon. The time is coming. We're now migrating a second component to FOF 3. If no changes are required expect a FOF 3 beta in April.

**Comment by Eighke** [comment]
Oki great. :)
