### ISSUE TITLE
Custom models doesn't consider declared fof.xml behaviors

### ISSUE THREAD

**Issue by fede91it** [akeeba/fof#500]
Given that `fof.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<fof>
	<common>
		<container>
			<option name="componentNamespace">Acme\Example</option>
		</container>

		<backend>
			<model name="*">
				<behaviors>Filters</behaviors>
			</model>
			<container>
				<option name="factoryClass">FOF30\Factory\MagicSwitchFactory</option>
			</container>
		</backend>
	</common>
</fof>
```

The declared `<behaviors>` work good with this component structure

```
<root>/administrator/component/com_example
	+-- View
	|	+-- Foobar
	+-- fof.xml
	+-- example.php
 ```

But they are not considered when you define a custom `DataModel` implementation

```
<root>/administrator/component/com_example
	+-- View
	|	+-- Foobar
	+-- Model
	|	+-- Foobar.php
	+-- fof.xml
	+-- example.php
 ```

In this case fof.xml is not considered and you must redeclare the behavior in the model `$config`

**Comment by nikosdion** [comment]
This makes perfect sense. The fof.xml configuration file is only used when an object is created automatically by the Magic or MagicSwitch factory. When you are writing code you are supposed to add your behaviours and other customisations in the constructor of your class.

This was a conscious choice. A big complaint with FOF 2 –both from the developers and internally– was that it performed too much magic. You had no control over your code unless you were really careful and take into account every possibility regarding configuration etc. With FOF 3 we put the developer in the controls. As a bonus you get much better performance since we don't have to go through the complex logic trying to figure out what you meant and usually guess wrong because a mind reader API is not available for PHP :)

**Comment by fede91it** [comment]
Great, fake alarm so :P
