### ISSUE TITLE
Cli generator for Scaffolding

### ISSUE THREAD

**Issue by Skullbock** [akeeba/fof#501]
# Introduction

When i was at #jab15 i attended the awesome talk "Look Mum, no Code!" (http://jandbeyond.org/programme.html?view=session&id=51&return=L3Byb2dyYW1tZS5odG1s) presentation by @nikosdion and saw for the first time the **saveScaffolding** feature of FOF3. 

In my daily work i use NodeJS a lot for some special projects, and i'm into a particular framework, called SailsJS (http://sailsjs.org/). This framework has a very neat feature that i'm missing every time i develop with Joomla! (and FOF of course), which is what they call a **generator** (http://sailsjs.org/#!/documentation/reference/cli/sailsgenerate.html). 

The new feature of saveScaffolding in FOF does exactly the same thing, but on the pageload of a particular view. This is not so handy when you need to build several views, or you need to build just some parts of the MVC (ie: just the read view of one MVC triad).

So i thought: what if we could do just like in sails:

```
fof generate api orders
```

and FOF automatically generates a Controller, Model and View (list, form, edit, read) for an Orders view, based on the database's layouts? 

# Possibile Syntax and Features

- **fof generate api orders**
Generate a full MVC Triad for the give view name. By default in the backend, but it could be done in the frontend too using *--frontend*

- **fof generate controller order**
Generate just a controller for the given view. By default in the backend, but it could be done in the frontend too using *--frontend*

- **fof generate model order**
Generate just a model for the given view. By default in the backend, but it could be done in the frontend too using *--frontend*

- **fof generate view order**
Generate every xml view for the given resource. By default in the backend, but it could be done in the frontend too using *--frontend*. Could also limit to a specific view with *--read --list --edit*

# RFC

I would like to know what you think about this and if you would change some feature / syntax before actually building this thing :+1:

**Comment by nikosdion** [comment]
There's a major different in Joomla!: we have a multi-tenant system, each component being its own application. So the first thing we need is creating a component skeleton. For example:
`fof generate app com_something --namespace="YourCompany\Something"`

It's also a good idea being able to create a repository structure, compatible with Akeeba Build Tools, but let's leave this out for now. We will make the script extensible, so no problem there.

Now we can move into creating the various items. All the generate commands need to specify the component name, e.g. `fof generate api com_something orders`.

The major issue I see is that the fof script needs to load Joomla! which means it has to be installed inside the site we're operating in. Therefore it would be called as something like
`php /var/www/html/mysite/cli/fof/fof.php app com_something`
That's not very user friendly unless an alias is used.

We could traverse the directories from the current backwards until we find Joomla!'s root. This allows us to get the site's configuration.php as well as accessing the component's fof.xml file.

However, I'd also like to be able to run this script from inside my repository: pulling up a terminal in phpStorm and typing `fof generate api orders` sounds neat. In this case we have three caveats:
* We need to know where to find the (dev) site this component lives in. We can have a `.fof` INI-style config file in the repository's root to tell us that, as well as all the path mappings (e.g. which repository folder do I put the back-end files in).
* How do we find this .fof file? Again, traverse directories from current working dir backwards until we find it is the only way I can think of.
* Since we inherently know which component we're operating on we must not ask the developer to type it. They need to type `fof generate api orders`, not `fof generate api com_something orders`.

How does that sound?

**Comment by Skullbock** [comment]
I like the idea of the generator for the component.
Reading your reply I put down some other ideas that could implement what
you say in a slightly different way. I'm writing from my iPad so i' sorry
if it's not presented as well as it should be

- I like the way composer and npm work in this case: having a "global" fof
tool that can be run simply as "fof generate" is convenient
- following composer again, the tool should first run "fof init" to create
a json file describing the component, like name, namespace, folders,
author, dev site location, etc.
It should also guide the developer asking questions to fill these
informations, having sensible defaults. Maybe it could even be possible to
integrate these informations in a section of the composer.json file so we
avoid creating yet another config file
- being inside the repo, as you said, we can skip the component part and
get the db info from the file at the step above



Il giorno mer 10 giu 2015 alle 20:07 Nicholas K. Dionysopoulos <
notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> ha scritto:

> There's a major different in Joomla!: we have a multi-tenant system, each
> component being its own application. So the first thing we need is creating
> a component skeleton. For example:
> fof generate app com_something --namespace="YourCompany\Something"
>
> It's also a good idea being able to create a repository structure,
> compatible with Akeeba Build Tools, but let's leave this out for now. We
> will make the script extensible, so no problem there.
>
> Now we can move into creating the various items. All the generate commands
> need to specify the component name, e.g. fof generate api com_something
> orders.
>
> The major issue I see is that the fof script needs to load Joomla! which
> means it has to be installed inside the site we're operating in. Therefore
> it would be called as something like
> php /var/www/html/mysite/cli/fof/fof.php app com_something
> That's not very user friendly unless an alias is used.
>
> We could traverse the directories from the current backwards until we find
> Joomla!'s root. This allows us to get the site's configuration.php as well
> as accessing the component's fof.xml file.
>
> However, I'd also like to be able to run this script from inside my
> repository: pulling up a terminal in phpStorm and typing fof generate api
> orders sounds neat. In this case we have three caveats:
>
>    - We need to know where to find the (dev) site this component lives
>    in. We can have a .fof INI-style config file in the repository's root
>    to tell us that, as well as all the path mappings (e.g. which repository
>    folder do I put the back-end files in).
>    - How do we find this .fof file? Again, traverse directories from
>    current working dir backwards until we find it is the only way I can think
>    of.
>    - Since we inherently know which component we're operating on we must
>    not ask the developer to type it. They need to type fof generate api
>    orders, not fof generate api com_something orders.
>
> How does that sound?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akeeba/fof/issues/501#issuecomment-110858713>.
>


-- 

Daniele Rosario

**Comment by nikosdion** [comment]
We could add the component information in the composer.json file, but we still need a .fof file. Unlike Composer which is completely standalone, the fof CLI tool needs to load files from a Joomla! site (framework, CMS libraries, FOF 3.x). In order to do that it needs an absolute filesystem path to the file. I don't want that committed to the repository. It is bad practice and makes it harder to collaborate. Putting that in a .fof file in the repository's root allows us to add this file to .gitignore and be done with it.

As for the information stored inside the composer.json of a component's repository, we need a few things we cannot easily deduce:
Name of the component, e.g. com_something
Location of back-end files, e.g. component/backend
Location of front-end files, e.g. component/frontend
Location of media files, e.g. component/media
Location of front-end translation files, e.g. translations/component/frontend
Location of back-end translation files, e.g. translations/component/backend

You don't need to set up the namespace in there. If you know where the back-end files directory is you can load fof.xml which already contains this information. Don't duplicate information.

Also, you must not put the dev site's path in that file. The dev site's path depends on the dev machine, not the component repository. That's why I'm saying this should be added in a .fof file. In the interest of not having to put a .fof file in every repository you could also have one in the user's home directory and use it as a fallback. Thus we'd only need to put one such file per dev machine and everything would "magically" fall into place.

For the same reasons we don't need to include the database connection information in our configuration files. Since we have a dev site we are reading its configuration.php file anyway and get a JDatabaseDriver object connected to the database for free. Don't duplicate information and don't store passwords in files you're supposed to commit to version control.

In the interest of making our lives easier we should also have a "fof getconfig devsite" command to return the dev site path. I could use that in the Common Phing Script <https://github.com/akeeba/buildfiles/tree/master/phing> to make `phing relink` work without specifying the dev site's path.

**Comment by Skullbock** [comment]
I totally agree, maybe i didn't express myself well (that's what you get when you write from the ipad on the couch at 12pm).

For sure the dev site path shouldn't be in the config file and should not be pushed in the repo.
And for sure the connection details will be fetched from the configuration.php using the site dev path.

The rest of the informations, like the repo structure, could be stored into the composer file.
Ok, let's start building this thing then :)

**Comment by nikosdion** [comment]
Sounds like a plan 👍🏻

**Comment by Skullbock** [comment]
Linking the WIP branch for this :)

https://github.com/Skullbock/fof/blob/feature/CliGenerator/cli/fof.php

**Comment by Skullbock** [comment]
First step done:
- Basic structure
- Help command
- Init command, that checks and suggests you to create a composer.json and guide you through the basic informations and create the right folders for you if necessary

Thoughts?

**Comment by nikosdion** [comment]
Between lines 72 and 74 you need to add the code which looks whether this is running inside a Joomla! site (based on getcwd(), NOT __DIR__), if not look for and parse the .fof file, then use that instead of __DIR__ to get the correct path to the site's cli directory.

**Comment by Skullbock** [comment]
Ah sure, i'm still in general testing phase, you're totally correct.

**Comment by Skullbock** [comment]
Something like this?
https://github.com/Skullbock/fof/commit/920c1834c6443fcce971e7a8fd5d7951ae7cdecd

**Comment by Skullbock** [comment]
Hi @nikosdion , sorry to bother you but i met a roadblock which i think you can guide me by.
When i have to create an instance for the Builder / Erector to create the xml files, i need to pass to it the Container instance (of course).

The issue with that is that the container automatically thinks it is inside a Joomla installation and loads everything for the given component searching JPATH_SITE and JPATH_ADMINISTRATOR, which is not what we want. 

I tried creating a dedicated container for this, but it ties deeply with the platform Service that again is tied with JPATH_SITE and JPATH_ADMINISTRATOR.

Do you see an easy way out?

**Comment by nikosdion** [comment]
Actually, it _is_ what we want. This is why I told you that you need to first add the discovery code between lines 72 to 74. This will allow you to know where the Joomla! site is stored, therefore populate JPATH_SITE and JPATH_ADMINISTRATOR. As a result FOF can now understand it runs under Joomla! CLI and locate the component's fof.xml, therefore initialising itself properly.

It's not a roadblock you've hit. You tried taking a shortcut but, really, there's nowhere to go through there :)

**Comment by Skullbock** [comment]
That i already did, but in this case is a bit different i think. The saveXML of the Builder class would save the file in the dev joomla installation instead of the component repo this way. This is not what we want right?

**Comment by nikosdion** [comment]
No, it actually *is* what we want. We expect the repository to be symlinked to the dev site, e.g. using Akeeba Build Tools.

**Comment by Skullbock** [comment]
Ah so you say: it creates the files into the site, but the folder of the component is symlinked so it is actually storing it into the repo folder. Got it.

**Comment by nikosdion** [comment]
Yep :)

**Comment by Skullbock** [comment]
Ok, so first step done!
Now it can also generate a browse form for both backend and frontend!

RFC from @nikosdion :) (sorry to bother, but want to do this in a way that's useful for everyone and not just me)

**Comment by nikosdion** [comment]
So far so good. It's time to refactor :) Each script command could be an observer. The main application could dispatch an event and let the observers handle it. This will allow us adding functionality without ending up with a gazillion lines file.

**Comment by Skullbock** [comment]
Good idea. It should trigger an even for whatever command?
Something like:

```php
$this->dispatcher->trigger('onFOFGeneratorCommand' . ucfirst($command));
```

**Comment by nikosdion** [comment]
This is what I was thinking. We could go into a full Dispatcher - Controller approach but I think that at least at this point it'd be an overkill.

**Comment by Skullbock** [comment]
That's ok for me.
I could also register a subfolder for the commands. Then register a plugin group for adding new commands. Would that be ok or did you have another way in mind?

**Comment by nikosdion** [comment]
Sounds good to me.

**Comment by Skullbock** [comment]
Tried a slightly different solution with autoloader. What do you think?

**Comment by nikosdion** [comment]
Even better with the autoloader.

**Comment by Skullbock** [comment]
Moved everything in the autoloader. Next week i'm going to add the read / edit forms :)

**Comment by nikosdion** [comment]
You're awesome! 👍🏻

**Comment by Skullbock** [comment]
Ok, i had some free time today. All view files generators are working.
Small recap of commands:

```
FOF3 Generator Usage:
fof init: Initialize a component
fof generate defaultview <view>: Create the backend form.default.xml file for the given view
fof generate formview <view>: Create the backend form.form.xml file for the given view
fof generate itemview <view>: Create the backend form.item.xml file for the given view
fof generate defaultview <view> --frontend: Create the frontend form.default.xml file for the given view
fof generate formview <view> --frontend: Create the frontend form.form.xml file for the given view
fof generate itemview <view> --frontend: Create the frontend form.item.xml file for the given view
fof setdevserver: Set the dev server location
fof help: Show this help
```

the command for now is actually **php fof.php**

RFC :)

**Comment by nikosdion** [comment]
It's already looking good. Now let's take it to the next level! (Note to self: [repository](https://github.com/Skullbock/fof/blob/feature/CliGenerator/cli/fof.php))

First I'd add a line to the top of the file:
```#!/bin/php```
and give the file 0755 permissions. This allows putting its directory to the PATH for easier access.

Second, I'd put the `FofApp` class into its own file and `require_once` it right after the initialisation code has run.

Thirdly, I'd add PHAR building support, see [how I did it in Remote Control CLI](https://github.com/akeeba/remotecli/blob/master/remotecli/remote.php). This would allow us to create an executable fof.phar.

Finally, if the script is running under PHAR I'd add a fof install global which would try copying fof.phar to /usr/local/bin or /usr/bin (depending on which one is in the current user's PATH).

**Comment by Skullbock** [comment]
Something like this?
https://github.com/Skullbock/fof/commit/61eeb517c9730d5ea1451a7786d1f557f9e7e7c3

**Comment by nikosdion** [comment]
Yup! I'm not sure if getcwd() works inside a PHAR archive. Have you tried it?

**Comment by Skullbock** [comment]
Yup it works. Now i added the phar and the toolset i used to generate it (box project) which seems very cool because it allows us to version the executable file itself :)

**Comment by nikosdion** [comment]
If I understand correctly you used http://box-project.org right? Awesome :)

**Comment by Skullbock** [comment]
Yup, seems awesome, and made the phar creation a breeze.
I tried using it with the phar archive in my /usr/local/bin directory and
it works with getcwd() so awesome.
Stiill a long way to go, but at least we have a proof of concept!

Do you have the next steps for controller / model creation or other ideas?

Daniele Rosario

Il giorno lun 15 giu 2015 alle ore 15:09 Nicholas K. Dionysopoulos <
notifications@github.com> ha scritto:

> If I understand correctly you used http://box-project.org right? Awesome
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akeeba/fof/issues/501#issuecomment-112063953>.
>
-- 
Daniele Rosario CTO Via F.Filzi, 56/A 36051 Creazzo (Vicenza) Tel.: +39
0444 1454934 Mob: +39 328 3017134 Immagine in linea 1

**Comment by nikosdion** [comment]
I'll have to write the code to auto-create controllers and models. So far I'm thinking that I could generate a few onBefore / onAfter events and add template code to show how you can limit execution to specific tasks. Frankly, I need user input for this feature. I am not sure what people would expect the code to do :(

**Comment by Skullbock** [comment]
IMHO we could just start with Model file (poissibily with relations auto setup) and type hints
FOr controllers, just an empty class file could be good

**Comment by nikosdion** [comment]
Can you do a PR of your code against the development branch of FOF 3 for me to merge, refactor and start extending?
