### ISSUE TITLE
Attach for N-N relations

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#510]
Nicholas,

In Laravel we can use `attach` and `detach` for N-N relation, do you think about implementing it (or maybe it is already done with another name?). Currently I don't see any method to manage it.

**Comment by nikosdion** [comment]
All many-to-many relations implement FOF30\Model\DataModel\Collection. Assuming the same User and Role relationship described in Laraven's documentation you can do the following in FOF 3:

```php
// Get the user record
$user->find(1);

// Add existing role
$role123 = $user->getContainer()->factory->model('Roles')->find(123);
$user->roles->add($role123);

// Add a brand new role
$newRole = $user->getContainer()->factory->model('Roles')->tmpInstance();
$newRole->bind(['expires' => true]);
$user->roles->add($newRole);

// Remove existing role
$user->roles->removeById(123);
```

All roles will be synchronised when you call `$user->save()`. See https://github.com/akeeba/fof/blob/development/fof/Model/DataModel/Relation/BelongsToMany.php#L321-321 for context. The order of events is:
* User record is saved
* Each one of the role records is saved
* The pivot table records for the user record ID are flushed (deleted)
* New pivot records for the user record ID and each one of the role IDs are created

Not exactly a performance superstar but it seems to work fine.

**Comment by Eighke** [comment]
Ok, I'll use that.

But if we have a lot of link in the same time (let say 50) it looks a bit overkill no?

* Load 1 User
* Load 50 Roles
* Save 1 User record
* Save 50 Roles
* Deleted X Roles in the pivot table
* Created 50 Roles in the pivot table

Instead of:
* Load 1 User
* Deleted X Roles in the pivot table
* Created 50 Roles in the pivot table

**Comment by nikosdion** [comment]
It's more complicated because you have to care about two things: a. the pivot table and b. the actual related records (roles).

You would need to know which roles have changed. This means that you need a special behaviour in the Role model to mark records as dirty. If you fail to do that everything falls apart.

When you try to save a record you'd have to do this:
* Walk through the collection to save dirty and new records
* Walk through the collection to get their IDs
* Query the database again to see which entries are in the pivot and store them in an array
* Walk through the array and sort it into added, removed (and ignore not changed records)
* Walk through the added array and run an INSERT query into the pivot table
* Walk through the removed array and run a DELETE query against the pivot table

If you have a "mark dirty" behaviour to only save a record if it's modified or new (blank ID) you can actually use the existing code with minimal modifications because it'd be simpler to read and just as fast: you already do a delete and an insert and you'd still need to do a delete and an insert.

The problem is that you need a behaviour to mark records as dirty and a Collection method to tell you if there are dirty records. The latter would violate the architecture because it depends on a specific model behaviour, i.e. it has a hard dependency on something that's not –and shouldn't be– part of the Model itself.

**Comment by Eighke** [comment]
> You would need to know which roles have changed.

My goal currently is just to attach existing Roles to a existing User. Without saving or updating the Roles or User. So I only need to know if the `Ids` I'm trying to link exists. I can just make an unique query for that.

Basicaly:
* Checking if the $ids exists (else exit)
* Getting the current entries inside the pivot table
* Adding the one that are not inside yet

Btw, with the code you propose I will need to do a foreach ... My code is currently something like:

```php
foreach ($ids as $id)
{
   $role = $user->getContainer()->factory->model('Roles')->find($id);
   $this->roles->add($role);
}

$this->save();
```

Where `$ids` is a list of 200 `id` to link. I'm sure it will timeout on the production server... I will try to use whereRaw, but it will still looping 200 times to add the relation. :/

**Comment by Eighke** [comment]
`where` looks better, so if we need to do the same thing as Laravel:

```php
$user = App\User::find(1);
$user->roles()->attach([1, 2, 3]);
```
We will have to do that:
```php
$user->find(1);
$roles = $user->getContainer()->factory->model('Roles')->tmpInstance();

$newRoles = $roles->where(
	$roles->getIdFieldName(), 'in', [1,2,3]
)->get();

foreach($newRoles as $newRole) {
	$user->roles->add($newRole);
}

$user->getRelations()->save('roles');
```

I'm still thinking it is a bit overkill if we need to attach many relations in a row.

For `detach` the code will be more light.

```php 
$user = App\User::find(1);
$user->roles()->detach([1, 2, 3]);
```
to
```php
$user->find(1);

foreach([1,2,3] as $roleId) {
	$user->roles->removeById($roleId);
}

$user->getRelations()->save('roles');
```

I didn't find yet a way for `sync`. I'll check later.

**Comment by nikosdion** [comment]
The problem is where you put the detach and attach methods. Remember, all relations in FOF are Collections. We'd have to either subclass DataModel\Collection or pollute it with attach / detach / sync methods which may not be safe for general use in collections.

Another way would be going through the RelationManager but this would lead to awkward stuff like `$user->getRelations()->attach('roles', [1, 2, 3]);` which is a bit of a drag.

I guess subclassing Collection would make more sense but it still bugs me to be honest.

**Comment by nikosdion** [comment]
Looking at it we can't implement attach and detach in FOF without breaking eager loading. Sorry.

**Comment by Eighke** [comment]
Urf :(

Ok, thank for checking. I'll go with my solution for now. I'll need to find something to manage the `sync`, do we have a `reset` or `removeAll` for the collection? I'll need to reset the collection before doing the `attach` thing.

**Comment by nikosdion** [comment]
Hm, no, there is no reset. You'd have to go an a loop to remove the items. Let me add a reset() method to the Utils\Collection class.

**Comment by nikosdion** [comment]
OK, done. You can now call ->reset() against the relation's Collection to flush its data.

**Comment by Eighke** [comment]
Great. :)

Thanks.

**Comment by Eighke** [comment]
Looks perfectly. `sync` is equal to:

```php
$user->find(1);

$user->roles->reset();

foreach([1,2,3] as $roleId) {
    $user->roles->removeById($roleId);
}

$user->getRelations()->save('roles');
```

I'll try to find some place in the wiki to add that.

**Comment by Eighke** [comment]
https://github.com/akeeba/fof/wiki/Model-relations#many-to-many-relationships

**Comment by nikosdion** [comment]
Thank you!
