### ISSUE TITLE
Case sensitive task mapping from fof.xml

### ISSUE THREAD

**Issue by fede91it** [akeeba/fof#564]
In `fof.xml` this doesn't work:

```xml
<frontend>
	<view name="author">
		<taskmap>
			<task name="edit">read</task>
		</taskmap>
	</view>
</frontend>
```
but that does:

```xml
<frontend>
	<view name="Author">
		<taskmap>
			<task name="edit">read</task>
		</taskmap>
	</view>
</frontend>
```

Why in this configuration area FOF is case sensitive?

**Comment by nikosdion** [comment]
Because FOF has always been case sensitive and the classes in FOF3 begin
with a capital letter. Of course if you cock it up and enter an all
lowercase default view and setup the lowercase view it will work, but only
because you completely cocked it up, not by design.

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.akeebabackup.com
Στις 24 Σεπ 2015 1:21 μ.μ., ο χρήστης "Federico Liva" <
notifications@github.com> έγραψε:

**Comment by fede91it** [comment]
I've understood, thank you NIcholas
