### ISSUE TITLE
FOF 2.x behaviors are not working in PHP 7

### ISSUE THREAD

**Issue by rameshelamathi** [akeeba/fof#593]
Hi

If we have one or more default behaviors (like filters, access), then FOF takes only the first behavior and ignores the rest.
Here are the results of tracing the issue so far:

While attaching,  F0FUtilsObservableDispatcher  -> attach method maintains the current position of the observers array at 0.
Line number 228 at fof/observable/dispatcher.php
$key = key($this->_observers);

The $key is always 0. 

I am stuck at this point now. :-(

**Comment by nikosdion** [comment]
Unfortunately FOF 2 is deprecated and on its way to being completely discontinued. For over a year we've been telling developers to upgrade to FOF 3. We are not going to address any further issues in FOF 2. My recommendation is to upgrade your components to FOF 3.

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by rameshelamathi** [comment]
Thank you Nicholas. 
We have already upgraded the components to FOF 3 and testing them right now. Will be releasing with FOF 3 by the end of this month. 

Some of our users are using the old version with FOF 2 and they reported the issue.  Since they customised their shops (unfortunately by editing core files against our recommendation), they could not update. We kind of a caught in the middle. Could not turn down their request :-( 
So trying to see if we can sort it out. 

It works good if we use just one behaviour (which is how the core component works and it works good in PHP 7). Some of the plugins add more than one behaviour to add additional functionality (like pricing calculators). That is when the issue starts.

Let me trace further and try to solve it. 

Thanks again for the quick response. Best in class and a great inspiration :-)
Ramesh

**Comment by nikosdion** [comment]
You were very, very close. If you read PHP 7's [backward incompatible changes notes](http://php.net/manual/en/migration70.incompatible.php) you'll see that foreach now doesn't change the internal array pointer. In the two foreach loops you traced one uses `end($this->_observers)`, the other doesn't. So if you pass a callback observer the `end($this->_observers)` code will set the array pointer to the end of the array. The other, lacking this code, would work on PHP 5 because the foreach above it would set the array pointer to the very end whereas under PHP 7 it wouldn't.  By adding `end($this->_observers)` we restore PHP 7 compatibility.

**Comment by rameshelamathi** [comment]
Thank you so much. You are awesome :-)

**Comment by nikosdion** [comment]
You're welcome :)
