### ISSUE TITLE
[Feature] Implementing a Container which can accept all extension types?

### ISSUE THREAD

**Issue by toroworx** [akeeba/fof#660]
The Container currently only supports components. How about modifying it so it also works with other extensions e.g. modules, plugins? Maybe by adding an additional getFoobarInstance() method for B/C. I am currently using it for retrieving plugin parameters (modified version of FOF's Params.php) and handling extension assignments (own implementation).

I have a working version of this, which looks summarized like this:

	/**
	 * Returns a Foobar container instance for a specific extension.
	 *
	 * Usage examples:
	 *
	 * $container = Container::getFoobarInstance('com_tags', 'component', null, $values);
	 * $container = Container::getFoobarInstance('vote', 'plugin', 'content', $values);
	 *
	 * @param   string	$name		The name of the extension you want to get a container for, e.g. 'com_foobar'.
	 * 								Corresponds to the element column of #__extensions.
	 * @param   string	$type		The extension type, e.g. 'component', 'module', 'plugin', 'library' etc.
	 * 								Corresponds to the type column of #__extensions.
	 * @param   string	$folder		The plugin folder. Only required for plugins.
	 * 								Corresponds to the folder column of #__extensions.
	 * @param   array   $values     Container configuration overrides you want to apply. Optional.
	 * @param   string  $section    The application section ('site', 'admin') you want to fetch. Any
	 * 								other value results in auto-detection.
	 *
	 * @return \FOF30\Container\Container
	 */
	public static function getFoobarInstance($name, $type, $folder = null, array $values = array(), $section = 'auto')

I assume backward compatibility is a must for FOF3 so it could be accomplished by adding the following methods: `getFoobarInstance()`, `makeFoobarInstance`, where `Foobar` could be e.g. `Extension`. No more `getFakeContainer()` needed then.

Please let me know your thoughts.

**Comment by nikosdion** [comment]
I disagree with this. The only true application -which can be instantiated in whole or in parts, multiple times, in a page load- is the Component.

Plugins are event handlers. This will be further clarified in Joomla! 4. You cannot and should not instantiate an event handler as an application. The event handler, however, may need to use the application's Models. Our container make sure that the required services for the application's Models are always present and ready in an expected state. Moreover, the Factory service in the container makes sure that you can always access said Models, be they concrete or auto-generated.

Modules are mistakes made 15 years ago :) A module's only purpose in life should be rendering a Component's View therefore it should have no instance. The fact that a module is not a class but an entry point file (like the component's entry point file) should have been a dead giveaway. Therefore a module should only be a "window" to an application, allowing multiple application instances (of the same or different applications) to be laid out on a page. Rendering a component's view is facilitated by the Container.

Templates are not to be instantiated either. They have an entry point file of a fixed name depending on the intended rendered information (index.php, component.php and error.php) and they handle output. As such they do not lend themselves to instantiation. I can't see why on Earth you'd want to reference a component in a template but, hey, if you want you can fetch it through the Container.

Libraries are most definitely not application by definition. If you need a "container for the library" you're doing something wrong.

File extensions are just a way to provide installable media and translation files. Any other use is monstrous. So they don't lend themselves to having a container as it makes no sense (no executable code to begin with).

Package extensions are meta-extensions so nothing to discuss here.

I can see why you are confused but that's all there is to it. You are confused. Instead of trying to deal with plugins and modules as top level applications (which is wrong) you could simply refactor `FOF30\Params\Params`. Instead of passing the entire container you could simply pass the db object and the extension information.

**Comment by toroworx** [comment]
Thanks a lot for your extensive feedback! I've read your response and I understand your approach, which seems like a good alternative. I didn't have the time and energy to continue with it though.
